Add paused, resumed, and seeked emitters.
lavacord/Lavacord pull request #16
Opened 2020-04-07 03:02 UTC by KareemRS

Very useful for duration played handling.
Not familiar with TS so corrections are likely needed, as well as additions to the interface section at the bottom.

2020-04-07 12:00 UTC, MrJacz requested changes
You will also need to add the events to the Interface for `Player`.

2020-04-07 12:00 UTC, MrJacz commented on src/lib/Player.ts
> +        if (this.listenerCount("paused") && pause === true) this.emit("paused");
```suggestion
        if (this.listenerCount("pause")) this.emit("pause", pause);
```

2020-04-07 12:00 UTC, MrJacz commented on src/lib/Player.ts
> +        if (this.listenerCount("resumed") && pause === false) this.emit("resumed");
```suggestion
```

2020-04-07 12:00 UTC, MrJacz commented on src/lib/Player.ts
> +        if (this.listenerCount("seeked")) this.emit("seeked", position);
```suggestion
        if (this.listenerCount("seek")) this.emit("seek", position);
```

2020-04-07 12:00 UTC, MrJacz commented
Please also fix the TSC & Typedoc errors. and remove the draft status

2020-04-09 01:37 UTC, KareemRS commented
Don't know whats causing the tsc error, unfortunately.

2020-04-09 08:42 UTC, MrJacz requested changes
Commit these suggestions and you should be good to go!

2020-04-09 08:42 UTC, MrJacz commented on src/lib/Player.ts
> +    on(event: "pause", listener: (data: LavalinkEvent) => void): this;
```suggestion
    on(event: "pause", listener: (pause: boolean) => void): this;
```

2020-04-09 08:42 UTC, MrJacz commented on src/lib/Player.ts
> +    on(event: "seek", listener: (data: LavalinkEvent) => void): this;
```suggestion
    on(event: "seek", listener: (position: number) => void): this;
```

2020-04-09 08:42 UTC, MrJacz commented on src/lib/Player.ts
> +    once(event: "pause", listener: (data: LavalinkEvent) => void): this;
```suggestion
    once(event: "pause", listener: (pause: boolean) => void): this;
```

2020-04-09 08:42 UTC, MrJacz commented on src/lib/Player.ts
> +    once(event: "seek", listener: (data: LavalinkEvent) => void): this;
```suggestion
    once(event: "seek", listener: (position: number) => void): this;
```

2020-04-09 08:42 UTC, MrJacz commented on src/lib/Player.ts
> +    off(event: "pause", listener: (data: LavalinkEvent) => void): this;
```suggestion
    off(event: "pause", listener: (pause: boolean) => void): this;
```

2020-04-09 08:42 UTC, MrJacz commented on src/lib/Player.ts
> +    off(event: "seek", listener: (data: LavalinkEvent) => void): this;
```suggestion
    off(event: "seek", listener: (position: number) => void): this;
```

2020-04-09 08:42 UTC, MrJacz commented on src/lib/Player.ts
> +    emit(event: "pause", data: LavalinkEvent): boolean;
```suggestion
    emit(event: "pause", pause: boolean): boolean;
```

2020-04-09 08:42 UTC, MrJacz commented on src/lib/Player.ts
> +    emit(event: "seek", data: LavalinkEvent): boolean;
```suggestion
    emit(event: "seek", position: number): boolean;
```

2020-04-09 20:51 UTC, karyeet reviewed
I think we're good now.

2020-04-10 04:07 UTC, MrJacz requested changes
Sorry one more thing

2020-04-10 04:07 UTC, MrJacz commented on src/lib/Player.ts
>      public seek(position: number): Promise<boolean> {
I think, this is a better idea, so it doesn't emit seek if the send doesn't actually send to lavalink. just to be safe
```suggestion
    public async seek(position: number): Promise<boolean> {
        const d = await this.send("seek", { position });
        if (this.listenerCount("seek")) this.emit("seek", position);
        return d;
    }
```

2020-04-10 04:08 UTC, MrJacz commented on src/lib/Player.ts
> +        if (this.listenerCount("seek")) this.emit("seek", position);
```suggestion
```

2020-04-10 04:08 UTC, MrJacz commented on src/lib/Player.ts
>          return this.send("seek", { position });
```suggestion
```

2020-04-10 04:08 UTC, MrJacz commented on src/lib/Player.ts
>      }
```suggestion
```

2020-04-10 04:09 UTC, MrJacz approved these changes
LGTM

2020-04-10 04:14 UTC, merged