Allow moving bots between channels.
lavacord/Lavacord pull request #67
Opened 2020-06-03 07:07 UTC by efindus

Currently when bot is moved from one channel to another player disconnects. This fixes the issue.

2020-06-03 10:19 UTC, MrJacz requested changes

2020-06-03 10:19 UTC, MrJacz commented on src/lib/Manager.ts
> +            if (this !== undefined) {
remove this

2020-06-03 10:19 UTC, MrJacz commented on src/lib/Manager.ts
> +                if (this.voiceStates !== undefined) {
remove this

2020-06-03 10:19 UTC, MrJacz commented on src/lib/Manager.ts
> +                    if (this.voiceStates.has(data.guild_id) !== false) {
```suggestion
                    if (this.voiceStates.has(data.guild_id)) {
```

2020-06-03 10:19 UTC, MrJacz commented on src/lib/Manager.ts
> +                        if (this.voiceStates.get(data.guild_id).channel_id !== undefined) {
```suggestion
                        if (this.voiceStates.get(data.guild_id)!.channel_id) {
```

2020-06-03 10:19 UTC, MrJacz commented on src/lib/Manager.ts
> +                            if (data.channel_id !== this.voiceStates.get(data.guild_id).channel_id) {
Make the channelID a variable instead of using getting it twice

2020-06-03 11:09 UTC, efindus commented
Yes! Finally!

2020-06-04 12:56 UTC, MrJacz commented
Now that I look at the code more and more, I was just thinking, If you remove the entire `if (data.channel_id) block does that work properly?

2020-06-04 13:55 UTC, efindus commented
```js
this.voiceServers.delete(data.guild_id);
this.voiceStates.delete(data.guild_id);
return Promise.resolve(false);
```

But what with this then? When change is about bot, it will always delete the data, meaning, when bot joins channel to play something, it deletes data immediately after, so nothing is being played and bot stays idle.

2021-01-05 13:20 UTC, closed without merging